name: design4you
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter_otp_text_field: ^1.1.3+2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  native_video_view: ^1.0.5
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
