name: design4you
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter_otp_text_field: ^1.1.3+2
  flutter:
    sdk: flutter
  widget_and_text_animator: ^1.1.5
  get: ^4.6.6
  file_picker: ^8.0.3
  auto_size_text: ^3.0.0
  animated_custom_dropdown: ^3.0.0
  syncfusion_flutter_datepicker: ^25.2.3
  permission_handler: ^11.3.1
  camera: ^0.11.0
  gal: ^2.3.0
  path_provider: ^2.1.3
  path: ^1.9.0
  dio: ^5.4.3+1
  sms_autofill:
  tab_container: ^3.5.3
  expansion_tile_group: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/CountryCodes.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
