name: design4you
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter_otp_text_field: ^1.1.3+2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  widget_and_text_animator: ^1.1.5
  get: ^4.6.6
  file_picker: ^8.0.3
  auto_size_text: ^3.0.0
  animated_custom_dropdown: ^3.0.0
  syncfusion_flutter_datepicker: ^25.2.3
  permission_handler: ^11.3.1
  camera: ^0.11.0
  gal: ^2.3.0
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
